FROM mcr.microsoft.com/playwright
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

# set work directory
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy project
COPY api ./api
COPY config ./config
COPY db ./db
COPY jobs ./jobs
COPY tools ./tools
COPY courses ./courses
COPY classifiers ./classifiers
COPY index ./index
COPY setup.py .
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt
RUN python setup.py install
RUN playwright install
RUN playwright install-deps

# install ffmpeg
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y ffmpeg

# Install GPU drivers
RUN pip uninstall torch -y
RUN pip cache purge
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
