name: Build
on:
  push:
    tags:
      - v*.*
      - v*.*.*

env:
  REGISTRY: ghcr.io

# docker build -f web-ui/Dockerfile web-ui -t kthgpt_frontend --no-cache
# docker build -f api/Dockerfile .
jobs:
  build_api_image:
    name: API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: actions/checkout@v3
        with:
          images: ${{ env.REGISTRY }}/kthgpt-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
