name: Test
on: push
jobs:
  PyTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt
        python setup.py develop

        # Install FFmpeg
        sudo apt-get -y update
        sudo apt-get install -y ffmpeg

    - name: Create Env
      run: |
        cp .env.example .env

    - name: Test with pytest
      run: |
        python -m pytest
