name: Test
on: push
jobs:
  test_python:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        python setup.py develop

        # Install FFmpeg
        sudo apt-get -y update
        sudo apt-get install -y ffmpeg

    - name: Create Testing Environment
      run: |
        cp .env.example .env

    - name: Test with PyTest
      run: |
        python -m pytest

  lint_python:
    name: Lint Pyton files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics --exclude venv

  lint_ts:
    name: Lint Typescript files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Modules
      run: |
        curl -fsSL https://get.pnpm.io/install.sh | sh -
        cd web-ui && pnpm install

    - name: Run eslint
      run: npm run lint
